print("Hi! Welcome to McDonald's.")
order = input("What do you want to order?")
if order == 'Burger':print("Starting off basic, i respect that.")
drinkorder = input("What drink would you like with that sir?")
if drinkorder == 'Sprite':print("Great choice, this is one of the most popular drinks in our menu!") 
if drinkorder == 'Coke':print("I always thought pepsi was the better drink.")
if drinkorder == 'Pepsi':print("Better then Coke")
finalcheck = input("Would you like to order anything else?")
byebye = print("Alright your all set! Pull up to the next window, thanks for coming!")